name: Release package to pub.dev
description: >
  Release a new package version to pub.dev and link to it from GitHub Releases.

inputs:
  path:
    description: Root directory of a Dart package
    default: '.'

runs:
  using: composite

  steps:
    - name: Download mobile-tools
      uses: actions/checkout@v3
      with:
        repository: leancodepl/mobile-tools
        path: mobile-tools

    - name: Add mobile-tools to $PATH
      shell: bash
      run: echo "$GITHUB_WORKSPACE/mobile-tools/bin" >> $GITHUB_PATH

    - name: Export release metadata as environment variables
      shell: bash
      run: |
        tag=${{ github.ref_name }}
        echo "RELEASE_NOTES=$(link_changelog $tag)" >> $GITHUB_ENV
        echo "IS_PRERELEASE=$(is_prerelease $tag)" >> $GITHUB_ENV

    # If `flutter` command is not available, use `dart pub publish`
    # If `flutter` command is available, use `flutter pub publish`
    # See also: https://github.com/dart-lang/setup-dart/issues/68
    - name: Publish to pub.dev
      shell: bash
      run: >
        cd "${{ inputs.path }}";
        if command -v flutter 1>/dev/null 2>&1; then
          flutter pub publish --force;
        else
          dart pub publish --force;
        fi

    - name: Create release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        body: '[See changelog on pub.dev](${{ env.RELEASE_NOTES }})'
        prerelease: ${{ env.IS_PRERELEASE }}
