name: prepare

on:
  push:
    branches: [master]
    tags-ignore: ["v*"]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run tests with BATS
        run: ./test/bats/bin/bats test/*.bats
