name: prepare

on:
  push:
    branches: [master]
    tags-ignore: ["v*"]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install shellcheck
        run: sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y shellcheck

      - name: Run tests with BATS
        run: ./test/bats/bin/bats test/*.bats

      - name: Run shellcheck for changed files
        run: git diff --name-only -z origin/master bin/ | xargs -0 shellcheck
